MAIL first checkin of SunOS/SPARC port
Added support for SunOS/SPARC platform using the C codegenerator.  It
passes all the regressions and a cross-self compile as well as normal
self compile on a SPARC.  I have not gone through a full bootstrap on
a SPARC because it is ridiculously slow (5 hours and counting) for the
version built with stubs to self compile.  There's still a lot of
cleanup and performance tuning left.

Here's a more detailed list of changes.

Added MLton.hostType Sun.

Changed the type of Random.{seed,useed} so that they return a word
option instead of a word.  They now return NONE if
/dev/{random,urandom} can't be read from (which may be the case on
SunOS).

Changed all shell scripts to /usr/bin/env bash.  I needed to do this
because sh on SunOS doesn't have !.

Rewrote add-cross and build-cross-gcc to work for multiple targets.

Moved handling of gcc flags from shell script into the compiler
proper.  This was done because we need different sets of flags for
different platforms.  It shouldn't cause any problems, since you can
always use -cc-opt to override them.

Eliminated Machine.{SetExnStackLocal,SetExnStackSlot,SetSlotExnStack},
which were vestigal.  They had been replaced by moves in the backend
a while ago.

Added -align-doubles {no|pad|skip}.  For now, only -align-doubles no
is implemented.  On SPARCs, which give a bus error for misaligned
doubles, this requires the C codegen to treat memory accesses to
doubles as two word accesses, which of course slows stuff down.  In
the near future, I plan to implement pad and skip.

Rewrote many of the switch usage messages so that <> is used to
indicate a variable that should be substituted for.

Eliminated -D.  You can use instead: -cc-opt '-D<SYM>'

Changed -build-constants to -build-constants {false|true}, for
uniformity's sake.

diff --git a/bin/add-cross b/bin/add-cross
--- a/bin/add-cross
+++ b/bin/add-cross
@@ -1,61 +1,70 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
 # This script adds a new crosscompiler target for MLton.
-# You may need to set installLibDir, crossHost, or cygwin.
-# This script builds an executable in the current directory that you must
-# run on the target machine.  This executable prints on standard output
-# the values of the compile time constants needed by the MLton when 
-# cross compiling.  You must place the output of running the executable in
-# $libDir/$crossHost/constants.
+#
+# It takes three arguments.
+#
+# 1. <crossHost>, will be used via the -b flag passed to the GCC
+# cross-compiler tools.  You must already have installed the GCC
+# cross-compiler tools.  This script does not do that, although you
+# may find the script build-cross-gcc helpful.  <crossHost> here
+# should be the same as target in build-cross-gcc.  Examples are
+# i386-pc-cygwin and sparc-sun-solaris.
+#
+# 2. {cygwin|sun}, specifies the kind of system.  There are only two
+# possibilities.
+#
+# 3. <machine> specifies a remote machine of the cross type.  After
+# cross compiling the runtime, this script will ssh to that machine to
+# get the values of the constants that the MLton basis library needs.
+# Of course, you must be able to ssh to this machine.
+#
+# You also may need to set $libDir, which determines where the
+# cross-compiler target will be installed.
 
 set -e
 
+die () {
+	echo >&2 "$1"
+	exit 1
+}
+
+usage () {
+	die "usage: $name <crossHost> {cygwin|sun} <machine>"
+}
+
+case "$#" in
+3)
+	crossHost="$1"
+	crossType="$2"
+	machine="$3"
+	;;
+*)
+	usage
+	;;
+esac
+
+name=`basename $0`
 original=`pwd`
 dir=`dirname $0`
 src=`cd $dir/.. && pwd`
 
-# libDir is the mlton lib directory where you would like the 
-# cross-compiler information to be installed.  If you have installed from the
-# rpms, this will usually be /usr/local/lib/mlton.  You must have write 
-# permission there. 
+# libDir is the mlton lib directory where you would like the
+# cross-compiler information to be installed.  If you have installed
+# from the rpms, this will usually be /usr/lib/mlton.  You must have
+# write permission there.
 
 lib="$src/build/lib"
 
-# crossHost will be used via the -b flag passed to the GCC cross-compiler tools.
-# You must already have installed the GCC cross-compiler tools.  This script
-# does not do that, although you may find the script build-cross-gcc helpful.
-# crossHost here should be the same as target in build-cross-gcc.
-crossHost='i386-pc-cygwin'
-
-# There are two possible types for the target machine: cygwin and linux. 
-# It should be obvious which of those you want.
-
-crossType='cygwin'
-
 # You shouldn't need to change anything below this line.
 
-name=`basename $0`
-
-function die {
-	echo >&2 $1
-	exit 1
-}
-
-function usage {
-	die "usage: $name"
-}
-
-case "$#" in
-0)
+case "$crossType" in
+cygwin|sun)
 ;;
 *)
-	usage
+	die "invalid crossType: $crossType"
 ;;
 esac
-
-if [ "$crossType" != 'linux' -a "$crossType" != 'cygwin' ]; then
-	die "invalid crossType: $crossType"
-fi
 
 PATH=$src/build/bin:$PATH
 
@@ -72,10 +81,14 @@ echo 'Making runtime.'
 exe='print-constants'
 echo 'Building print-constants executable.'
 (
-	mlton -build-constants >$exe.c
-	mlton -output $original/$exe.exe -host $crossHost $exe.c
+	mlton -build-constants true >$exe.c
+	mlton -output $original/$exe -host $crossHost $exe.c
 	rm -f $exe.c
 ) || die "Unable to build $exe executable."
 
-echo "You must now run $exe.exe on the $crossHost machine"
-echo "and put the output in $lib/$crossHost/constants."
+echo "Running print-constants on $machine."
+tar cf - $exe |
+	ssh $machine "tar xf - && ./$exe && rm -f $exe" \
+	>"$lib/$crossHost/constants"
+
+rm -f $original/$exe
diff --git a/bin/build-cross-gcc b/bin/build-cross-gcc
--- a/bin/build-cross-gcc
+++ b/bin/build-cross-gcc
@@ -1,52 +1,82 @@
-#!/bin/sh
+#!/usr/bin/env bash
 
-# This script builds and installs a gcc cross-compiler with a cygwin target.
-#
-# It requires that you have obtained the following packages, whose
-# tarfiles shoud be in the current directory:
-#	binutils, cygwin, gcc, w32api
-# You can find ftp sites to download binutils and gcc-core at gnu.org.
-# I got cygwin and w32api by installing cygwin in a Windows machine (using
-# Cygwin's setup.exe program) and then getting the bzip'ed tar files out of
-# their Cygwin packages dir.
+# This script builds and installs a gcc cross compiler.
+
+# It has been used to build cross compilers from Linux to Cygwin and
+# from Linux to SunOS.  It is unlikely that this script will work
+# out-of-the-box.  It is only intended as a template.  You should read
+# through it and understand what it does, and make changes as
+# necessary.  Feel free to add another targetType if you modify this
+# script for another target.
 
 set -e
-
-# You may need to change the version numbers below.
-# You also might want to change the installation prefix.
-#
-# I had problems with cygwin-1.3.18-1, since its libcygwin.a contained a
-# a file, pseudo-reloc.o, with some strangeness that binutils didn't 
-# correctly handle.
-
-binutils='binutils-2.12'
-cygwin='cygwin-1.3.17-1'
-gccVers='2.95.3'
-gcc="gcc-$gccVers"
-gccTar="gcc-core-$gccVers.tar"
-w32api='w32api-2.1-1'
-
-root=`pwd`
-target='i386-pc-cygwin'
-prefix='/usr'
-
-name=`basename $0`
 
 die () {
 	echo >&2 "$1"
 	exit 1
 }
 
+root=`pwd`
+name=`basename $0`
+
 usage () {
-	die "usage: $name"
+	die "usage: $name {cygwin|sun}"
 }
 
 case "$#" in
-0)
+1)
+	case "$1" in
+	cygwin|sun)
+		targetType="$1"
 	;;
+	*)
+		usage
+	;;
+	esac
+;;
 *)
 	usage
-	;;
+esac
+
+# You may want to change the installation prefix, which is where the
+# script will install the cross-compiler tools.
+prefix='/usr'
+
+# You must have have the sources to binutils and gcc, and place the
+# tarfiles in the current directory.  You can find ftp sites to
+# download binutils and gcc-core at gnu.org.  You may need to change
+# the version numbers below to match what you download.
+binutils='binutils-2.12'
+gccVers='2.95.3'
+gccTar="gcc-core-$gccVers.tar"
+
+# You may want to set the target.
+case "$targetType" in
+cygwin)
+	target='i386-pc-cygwin'
+	# For Cygwin, we also need the cygwin and w32api packages,
+	# which contain necessary header files and libraries.  I got
+	# them by installing cygwin in a Windows machine (using #
+	# Cygwin's setup.exe program) and then getting the bzip'ed tar
+	# files out of their Cygwin packages dir.  I had problems with
+	# cygwin-1.3.18-1, since its libcygwin.a contained a file,
+	# pseudo-reloc.o, with some strangeness that binutils didn't
+	# correctly handle.
+	cygwin='cygwin-1.3.17-1'
+	w32api='w32api-2.1-1'
+;;
+sun)
+	target='sparc-sun-solaris'
+	# For sun, we assume that you have already copied the includes
+	# and libraries from a SunOS machine to the host machine.
+	if ! [ -d "$prefix/$target/include" -a -d "$prefix/$target/lib" ]; then
+		die "Must create $prefix/$target/{include,lib}."
+	fi
+	# The GCC tools expect limits.h to be in sys-include, not include.
+	( cd $prefix/$target && 
+		mkdir -p sys-include &&
+		mv include/limits.h sys-include )
+;;
 esac
 
 exists () {
@@ -57,19 +87,24 @@ exists () {
 
 echo 'Checking that needed files exist.'
 exists $binutils.tar
-exists $cygwin.tar
 exists $gccTar
-exists $w32api.tar
-
-echo 'Copying include files and libraries needed by cross compiler.'
-cd $root
-mkdir -p cygwin
-cd cygwin
-tar x <../$cygwin.tar
-tar x <../$w32api.tar
-mkdir -p $prefix/$target || 
-	die "Cannot create $prefix/$target."
-(cd usr && tar c include lib) | (cd $prefix/$target/ && tar x)
+case "$targetType" in
+cygwin)
+	exists $cygwin.tar
+	exists $w32api.tar
+	echo 'Copying include files and libraries needed by cross compiler.'
+	cd $root
+	mkdir -p cygwin
+	cd cygwin
+	tar x <../$cygwin.tar
+	tar x <../$w32api.tar
+	mkdir -p $prefix/$target || 
+		die "Cannot create $prefix/$target."
+	(cd usr && tar c include lib) | (cd $prefix/$target/ && tar x)
+;;
+*)
+;;
+esac
 
 echo 'Building binutils.'
 cd $root
@@ -89,10 +124,13 @@ cd $root
 tar x <$gccTar
 mkdir -p build-gcc
 cd build-gcc
-../$gcc/configure --enable-languages=c --prefix=$prefix --target=$target \
-	>$root/configure-gcc-log 2>&1 ||
+../gcc-$gccVers/configure \
+	--enable-languages=c \
+	--prefix=$prefix \
+	--target=$target \
+	>$root/configure-gcc-log 2>&1 || 
 	die "Configure of gcc failed."
-make all install >$root/build-gcc-log 2>&1 ||
+make all install >$root/build-gcc-log 2>&1 || 
 	die "Build of gcc failed."
 
 echo 'Success.'
