This is the first set of changes in getting the cross-compiler to Cygwin working.  I'm not there yet, but many of the regressions pass with the C backend.  Nothing works yet with the native backend, but it looks like an easy fix.
I reorganized the directory structure so that when building MLton
files are no longer placed outside of the sources directory (they used
to be placed in ../lib ../include and ../bin).  Along the way, I added
the ability to support multiple hosts (cygwin, linux) simultaneously.
Now everything needed for running lives in the "build" subdirectory,
which looks like this:

	bin/
		mlton
		mllex
		mlyacc
		mlprof
	lib/
		mlton-compile
		world.mlton
		host1/
			*.a
			include/
		host2/
			*.a
			include/
		...

When installing, bin goes to /usr/local/bin and lib goes to
/usr/local/lib/mlton.

Right now, there are two hosts: i686-pc-linux-gnu and i686-pc-cygwin.
I modified the runtime to support a HOST variable that specifies the
host that the runtime should be built for.  There are also a few #if's
in the runtime sources to behave differently depending on whether
__CYGWIN__ or __linux__ is defined.  Most everything appears to be
supported under cygwin, except for signals and ptrace, but there is
still more testing todo.

Because I don't want to depend on the user to install a cross-compiled
gmp, I added the gmp sources back to the runtime directory, and the
runtime make will make libgmp.a for use by the cygwin backend.

Maybe it's a bit silly to not require a cross-compiled gmp, since I am
requiring the user to install a gcc cross-compiler.  I added a script
that I used to build the cross-compiler to the doc directory, and I
will add link to it in the user guide cross-compiler section, when
that exists.

All of this is driven by the new -host flag to mlton, which can take
either "cygwin" or "linux" as an argument.

One question that I have is what's the right thing to do for normal
compiles.  Right now I have references to i686-pc-linux-gnu in several
places where gcc is called (both in the runtime and from the
compiler).  I am guessing that the right thing to do is either to drop
them and leave the host implicit for normal compiles, or to figure the
build host type out dynamically.

diff --git a/bin/make-rpms b/bin/make-rpms
--- a/bin/make-rpms
+++ b/bin/make-rpms
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash -x
 
 # This script makes binary and source RPMs in topdir (your RPM _topdir).
 # It can either grab the sources from the CVS repository or from a local
@@ -8,9 +8,13 @@
 
 name=`basename $0`
 
-function usage() {
-	echo >&2 "usage: $name [-home dir] [-local dir] topdir"
+function die() {
+	echo >&2 $1
 	exit 1
+}
+
+function usage() {
+	die "usage: $name [-home dir] [-local dir] topdir"
 }
 
 home='no'
@@ -53,33 +57,39 @@ version=`date +%Y%m%d`
 release="1"
 package="mlton-$version-$release"
 
+function tar.read {
+	tar -p -xf - "$@"
+}
+
+function tar.write {
+	tar -p -cf - "$@"
+}
+
 echo 'Cleaning up'
 root="$topdir"
-src="$root/SOURCES/mlton-$version/src"
+src="$root/SOURCES/mlton-$version"
 cd $root
 mkdir -p BUILD RPMS/i386 SOURCES SPECS SRPMS
 cd $root/SOURCES
 rm -rf mlton-$version
-mkdir mlton-$version
-cd mlton-$version
-mkdir bin lib include
 if [ $local = 'yes' ]; then
 	echo 'Getting local sources'
-	mkdir src
-	(cd $localDir && tar.write .) | (cd src && tar.read && make clean)
+	mkdir mlton-$version
+	(cd $localDir && tar.write .) | 
+		(cd mlton-$version && tar.read && make clean)
 else
  	echo 'Checking out sources'
- 	cvs -Q co -d src mlton
- 	if [ ! -d src/basis-library ]; then
+ 	cvs -Q co -d mlton-$version mlton
+ 	if [ ! -d mlton-$version/basis-library ]; then
  		echo >&2 'Could'\''t check out sources.'
 		exit 1
  	fi
  	cvs rtag -d "release-$version" mlton
- 	(cd src && cvs tag "release-$version")
- 	cvs -Q release src
+ 	(cd mlton-$version && cvs tag "release-$version")
+ 	cvs -Q release mlton-$version
 fi
-find src -type d | grep CVS | xargs rm -rf
-find src -type f | grep cvsignore | xargs rm -f
+find mlton-$version -type d | grep CVS | xargs rm -rf
+find mlton-$version -type f | grep cvsignore | xargs rm -f
 
 function doInst() {
 	sed "s/\(.*\)VERSION\(.*\)/\1$version\2/" <$1 >z
@@ -115,7 +125,8 @@ rm -rf mlton-$version
 
 echo 'Building rpms'
 (
-	time rpm -ba --quiet --clean $root/SPECS/mlton.spec
+	time rpm -ba --quiet --clean $root/SPECS/mlton.spec ||
+		die 'rpm build failed'
 	touch $root/RPMS/i386/$package.i386.rpm $root/SRPMS/$package.src.rpm
 )
 
diff --git a/bin/mlton b/bin/mlton
--- a/bin/mlton
+++ b/bin/mlton
@@ -1,10 +1,8 @@
-#!/bin/sh
+#!/bin/bash
 
 # This script calls MLton.
 
-root='/usr/local/lib/mlton'
-include="$root/include"
-lib="$root/lib"
+lib='/usr/local/lib/mlton'
 gcc='gcc'
 mlton="$lib/mlton-compile"
 world="$lib/world.mlton"
@@ -31,11 +29,12 @@ doit () {
 	elif [ -s "$njHeap" ]; then
 		exec "$nj" @SMLload="$njHeap" "$@"
 	fi
-	echo 'Unable to run MLton.  Check that root is set properly.' >&2
+	echo 'Unable to run MLton.  Check that lib is set properly.' >&2
 	exit 1
 }
 
-doit "$root" "$gcc" -w -fomit-frame-pointer -fno-strength-reduce \
+doit "$lib" i686-pc-cygwin i686-pc-linux-gnu \
+	"$gcc" -w -fomit-frame-pointer -fno-strength-reduce \
 	-mcpu=pentiumpro -malign-loops=2 -malign-jumps=2 -malign-functions=5 \
 	-fschedule-insns -fschedule-insns2 END \
-	-I"$include" -include mlton.h -L"$lib" -lgmp -lm "$@"
+	-include mlton.h -lgmp -lm "$@"
diff --git a/bin/regression b/bin/regression
--- a/bin/regression
+++ b/bin/regression
@@ -1,30 +1,41 @@
-#!/bin/sh
+#!/bin/bash
 
 # This script runs the regression tests in src/regression.
 # It also compiles the tests in benchmark/tests
 
 name=`basename $0`
 
-function usage() {
-	echo >&2 "usage: $name"
+function usage {
+	echo >&2 "usage: $name [-cross] [-run-only]"
 	exit 1
 }
 
-case "$#" in
-0)
-	;;
-*)
-	usage
-	;;
-esac
+cross='no'
+runOnly='no'
+while [ "$#" -gt 0 ]; do
+	case "$1" in
+	-cross)
+		cross='yes'
+		shift
+		;;
+	-run-only)
+		runOnly='yes'
+		shift
+		;;
+	*)
+		usage
+		;;
+	esac
+done
 
 dir=`dirname $0`
-root=`cd $dir/../.. && pwd`
-src="$root/src"
-lib="$root/lib"
-bin="$root/bin"
+src=`cd $dir/.. && pwd`
+bin="$src/build/bin"
 mlton="$bin/mlton"
-flags='-type-check true -native true -gc-check first'
+flags='-type-check true -native false -gc-check first'
+if [ $cross = 'yes' ]; then
+	flags="$flags -host cygwin"
+fi
 cont='callcc.sml callcc2.sml callcc3.sml'
 signal='signals.sml'
 thread='thread0.sml thread1.sml thread2.sml mutex.sml prodcons.sml same-fringe.sml timeout.sml'
@@ -33,81 +44,81 @@ tmp=/tmp/z.regression.$$
 log=$src/regression-log
 PATH=.:$PATH
 
-(
-	cd $src/regression
-	for f in `ls *.sml`
-	do
-		f=`basename $f .sml`
+cd $src/regression
+for f in `ls *.sml`; do
+	f=`basename $f .sml`
+	case "$f" in
+	cobol|serialize|testdyn2)
+		echo "skipping $f"
+	;;
+	*)
+			echo "testing $f"
 		case "$f" in
-		cobol|serialize|testdyn2)
-			echo "skipping $f"
+		exnHistory*)
+			extraFlags="-exn-history true"
 		;;
 		*)
- 			echo "testing $f"
-			case "$f" in
-			exnHistory*)
-				extraFlags="-exn-history true"
-			;;
-			*)
-				extraFlags=""
-			;;
-			esac
+			extraFlags=""
+		;;
+		esac
+		if [ $runOnly = 'no' ]; then
 			$mlton $flags $extraFlags $f.sml
 			if [ $? -ne 0 ]; then
 				echo "compilation of $f failed"
-#				exit 1
-			elif [ ! -r $f.nonterm ]; then
-				$f >$tmp 2>&1
-				if [ -r $f.ok ]; then
-					diff $f.ok $tmp
-				fi
+				exit 1
 			fi
-			rm -f $f $f.ssa $f.c
-		;;
-		esac
-	done 
-	make clean > /dev/null
-        cd $src/benchmark/tests
-	for f in `ls *.sml`
-	do
-		f=`basename $f .sml`
-		tmpf=/tmp/$f.$$
-		case "$f" in
-		fxp)
-			echo "skipping $f"
-		;;
-		*)
- 			echo "testing $f"
-			echo "val _ = Main.doit ()" | cat $f.sml - > $tmpf.sml
-			$mlton $flags $tmpf.sml
-			if [ $? -ne 0 ]; then
-				echo "compilation of $f failed"
+		fi
+		if [ ! -r $f.nonterm -a $cross = 'no' ]; then
+			$f >$tmp 2>&1
+#			rm -f $f
+			if [ -r $f.ok ]; then
+				diff $f.ok $tmp
 			fi
-			rm -f $tmpf $tmpf.sml
-		;;
-		esac
-	done 
-	make clean > /dev/null
-	cd $src
-	for f in mllex mlyacc mlprof
-	do
-	    tmpf=/tmp/$f.$$
-	    cd $src/$f
-	    case "$f" in
-	    foobar)
-		    echo "skipping $f"
-	    ;;
-	    *)
-		    echo "testing $f"
-		    make -W $f > /dev/null
-		    $mlton $flags -o $tmpf $f.cm
-		    if [ $? -ne 0 ]; then
-				echo "compilation of $f failed"
-		    fi
-		    rm -f $tmpf
-	    ;;
-	    esac
-      done
-) 2>&1 | tee $log
+		fi
+	;;
+	esac
+done 
+if [ $cross = 'no' ]; then
+	make clean >/dev/null
+fi
+cd $src/benchmark/tests
+for f in `ls *.sml`; do
+	f=`basename $f .sml`
+	tmpf=/tmp/$f.$$
+	case "$f" in
+	fxp)
+		echo "skipping $f"
+	;;
+	*)
+			echo "testing $f"
+		echo "val _ = Main.doit ()" | cat $f.sml - > $tmpf.sml
+		$mlton $flags $tmpf.sml
+		if [ $? -ne 0 ]; then
+			echo "compilation of $f failed"
+		fi
+		rm -f $tmpf $tmpf.sml
+	;;
+	esac
+done 
+make clean > /dev/null
+cd $src
+for f in mllex mlyacc mlprof; do
+    tmpf=/tmp/$f.$$
+    cd $src/$f
+    case "$f" in
+    foobar)
+	    echo "skipping $f"
+    ;;
+    *)
+	    echo "testing $f"
+	    make -W $f > /dev/null
+	    $mlton $flags -o $tmpf $f.cm
+	    if [ $? -ne 0 ]; then
+			echo "compilation of $f failed"
+	    fi
+	    rm -f $tmpf
+    ;;
+    esac
+done
 
 rm -f $tmp
