Systematically made the following changes to all shell script I found:
1. Quote path variables
	"mkdir $x/bar" won't work if $x includes shell specials ("; '&...)
	This happens in both shell scripts and Makefiles

2. Generally tried to remove `cmd` usage wherever possible
	This breaks any filenames in the output. eg: `ls` is particularly
	bad and will mess up file names with spaces in them. Consider:
	for i in `ls`; do echo $i; done
	for i in *; do echo $i; done
	The first will print "foo\nbar\n" for a file "foo bar".
	The second will correctly print "foo bar\n"

3. Changed handling of shell arguements which are passed through
	Shell scripts had often broken appart and/or removed escapes.
	This problem would also affect filenames, for example:
	mlton @MLton cache="/Users/wes terpstra/cache" -- ...
	would break the option appart into two distinct halves:
		"/Users/wes
		terpstra/cache"
	The problem comes from the args="xxx $args" idiom.
	To preserve these values, you can use bash arrays (man bash).

4. Potentially modified the behaviour of bin/regression
	A comment previously stated:
                #   Must use $f.[0-9].[cS], not $f.*.[cS], because the
                #   latter will include other files, e.g. for finalize,
                #   it will also include finalize.2.
	My testing shows this to be false. Furthermore, the work-around:
                files="$f.[0-9].[cS]"
                if [ 0 -ne `ls $f.[0-9][0-9].[cS] 2>/dev/null | wc -l` ]; then 
                        files="$files $f.[0-9][0-9].[cS]"
                fi
	will break on a filename with spaces or shell specials.
	The problem is again assigning a list to a string variable.
	A way to do this correctly would've been:
		files=($f.[0-9].[cS])
	which creates a bash array with these values.
	However, then concatenating a second bash array for the 'if' case
	is a lot of work when a simpler solution is to use $f.*.[cS]



SVN r4515

diff --git a/bin/regression b/bin/regression
--- a/bin/regression
+++ b/bin/regression
@@ -5,7 +5,7 @@
 
 # set -e
 
-name=`basename $0`
+name=`basename "$0"`
 
 usage () {
         echo >&2 "usage: $name [-cross target] [-run-only target] [-short] [-skip-to reg] [mlton flags ...]"
@@ -17,6 +17,7 @@ fail='false'
 runOnly='false'
 short='false'
 skipTo=''
+declare -a flags
 while [ "$#" -gt 0 ]; do
         case "$1" in
         -cross)
@@ -54,20 +55,24 @@ while [ "$#" -gt 0 ]; do
                 shift
                 ;;
         *)
-                flags="$@"
-                break
+                flags[${#flags[@]}]="$1"
+		shift
                 ;;
         esac
 done
 
-dir=`dirname $0`
-src=`cd $dir/.. && pwd`
+dir=`dirname "$0"`
+src=`cd "$dir/.." && pwd`
 bin="$src/build/bin"
 lib="$src/build/lib"
 mlton="$bin/mlton"
-flags="-type-check true $flags"
+flags[${#flags[@]}]="-type-check"
+flags[${#flags[@]}]="true"
 if $cross; then
-        flags="$flags -target $crossTarget -stop g"
+	flags[${#flags[@]}]="-target"
+	flags[${#flags[@]}]="$crossTarget"
+	flags[${#flags[@]}]="-stop"
+	flags[${#flags[@]}]="-g"
 fi
 cont='callcc.sml callcc2.sml callcc3.sml once.sml'
 flatArray='finalize.sml flat-array.sml flat-array.2.sml'
@@ -76,23 +81,23 @@ signal='finalize.sml signals.sml signals2.sml suspend.sml weak.sml'
 thread='thread0.sml thread1.sml thread2.sml mutex.sml prodcons.sml same-fringe.sml timeout.sml'
 world='world1.sml world2.sml world3.sml world4.sml world5.sml world6.sml'
 tmp=/tmp/z.regression.$$
-PATH=$bin:$src/bin/.:$PATH
+PATH="$bin:$src/bin/.:$PATH"
 
-eval `$lib/platform`
+eval `"$lib/platform"`
 
 compFail () {
-        echo "compilation of $f failed with $flags"
+        echo "compilation of $f failed with ${flags[*]}"
 }
 
-$mlton -verbose 1 || echo 'no mlton present'
-echo "flags = $flags"
+"$mlton" -verbose 1 || echo 'no mlton present'
+echo "flags = ${flags[*]}"
 
-cd $src/regression
+cd "$src/regression"
 
 if $fail; then
-        for f in `ls fail/*.sml`; do
+        for f in fail/*.sml; do
                 echo "testing $f"
-                ( $mlton $flags -stop tc $f >/dev/null 2>&1 &&
+                ( "$mlton" "${flags[@]}" -stop tc "$f" >/dev/null 2>&1 &&
                         echo "compilation of $f should have failed but did not" ) ||
                         true
         done
@@ -109,8 +114,8 @@ case $crossTarget in
 ;;
 esac
 
-for f in `ls *.sml`; do
-        f=`basename $f .sml`
+for f in *.sml; do
+        f=`basename "$f" .sml`
         if [ "$skipTo" != "" ]; then
                 if [ "$skipTo" != "$f" ]; then
                         echo "skipping $f"
@@ -161,15 +166,14 @@ for f in `ls *.sml`; do
                                 \"nonexhaustiveMatch ignore\"
                                 \"redundantMatch ignore\"
                         in $f.sml 
-                        end" >$mlb
-                cmd="$mlton $flags $extraFlags -output $f $mlb"
-                eval $cmd
-                rm $mlb
+                        end" >"$mlb"
+                "$mlton" "${flags[@]}" $extraFlags -output "$f" "$mlb"
                 if [ "$?" -ne '0' ] || ((! $cross) && [ ! -x "$f" ]); then
-                        compFail $f
+                        compFail "$f"
                 fi
+                rm "$mlb"
 	else
-                case $crossTarget in
+                case "$crossTarget" in
                 *mingw)
                         libs='-lws2_32 -lkernel32 -lpsapi -lnetapi32'
                 ;;
@@ -181,27 +185,26 @@ for f in `ls *.sml`; do
                 ;;
                 esac
                 libs="-lmlton -lgmp $libs -lgdtoa -lm"
-                # Must use $f.[0-9].[cS], not $f.*.[cS], because the
-                # latter will include other files, e.g. for finalize,
-                # it will also include finalize.2.
-                files="$f.[0-9].[cS]"
-                if [ 0 -ne `ls $f.[0-9][0-9].[cS] 2>/dev/null | wc -l` ]; then 
-                        files="$files $f.[0-9][0-9].[cS]"
-                fi
-                gcc -o $f -w -O1                                \
+		# OLD COMMENT:
+                #   Must use $f.[0-9].[cS], not $f.*.[cS], because the
+                #   latter will include other files, e.g. for finalize,
+                #   it will also include finalize.2.
+		# I think this is untrue, and have dropped it as the work-
+		# around used was unsafe for special characters.
+                gcc -o "$f" -w -O1                              \
                         -I "../build/lib/include"               \
                         -L"../build/lib/$crossTarget"           \
                         -L/usr/pkg/lib                          \
                         -L/usr/local/lib                        \
-                        $files $libs
+                        "$f".*.[cS] $libs
 	fi
-        if [ ! -r $f.nonterm -a $cross = 'false' -a -x $f ]; then
+        if [ ! -r "$f".nonterm -a $cross = 'false' -a -x "$f" ]; then
                 nonZeroMsg='Nonzero exit status.'
 		if $forMinGW; then
                        nonZeroMsg="$nonZeroMsg"'\r'
 		fi
-                ( ./$f || echo -e "$nonZeroMsg" ) >$tmp 2>&1 
-                if [ -r $f.ok ]; then
+                ( "./$f" || echo -e "$nonZeroMsg" ) >$tmp 2>&1 
+                if [ -r "$f.ok" ]; then
                         compare="$f.$HOST_ARCH-$HOST_OS.ok"
                         if [ ! -r $compare ]; then
                                 compare="$f.ok"
@@ -210,8 +213,8 @@ for f in `ls *.sml`; do
                                 compare="$f.sed.ok"
                                 /c/cygwin/bin/sed 's/$/\r/' <"$f.ok" >"$compare"
 			fi
-                        if ! diff $compare $tmp; then
-                                echo "difference with $flags"
+                        if ! diff "$compare" "$tmp"; then
+                                echo "difference with ${flags[*]}"
                         fi
                 fi
         fi
@@ -220,47 +223,47 @@ if $cross || $runOnly || $short; then
         exit 0
 fi
 mmake clean >/dev/null
-cd $src/benchmark/tests
-for f in `ls *.sml`; do
-        f=`basename $f .sml`
-        tmpf=/tmp/$f.$$
+cd "$src/benchmark/tests"
+for f in *.sml; do
+        f=`basename "$f" .sml`
+        tmpf="/tmp/$f.$$"
         case "$f" in
         fxp|hamlet)
                 echo "skipping $f"
         ;;
         *)
                         echo "testing $f"
-                echo "val _ = Main.doit 0" | cat $f.sml - > $tmpf.sml
-                $mlton -output $tmpf $flags                     \
+                echo "val _ = Main.doit 0" | cat "$f.sml" - > "$tmpf.sml"
+                $mlton -output "$tmpf" "${flags[@]}"            \
                         -default-ann 'nonexhaustiveMatch ignore'\
                         -default-ann 'redundantMatch ignore'    \
-                        $tmpf.sml
+                        "$tmpf.sml"
                 if [ $? -ne 0 ]; then
-                        compFail $f
+                        compFail "$f"
                 fi
-                rm -f $tmpf $tmpf.sml
+                rm -f "$tmpf" "$tmpf.sml"
         ;;
         esac
 done 
 mmake clean >/dev/null
-cd $src
+cd "$src"
 for f in mllex mlyacc mlprof; do
-    tmpf=/tmp/$f.$$
-    cd $src/$f
+    tmpf="/tmp/$f.$$"
+    cd "$src/$f"
     case "$f" in
     foobar)
             echo "skipping $f"
     ;;
     *)
         echo "testing $f"
-        mmake -W $f >/dev/null
-        $mlton $flags -output $tmpf $f.mlb
+        mmake -W "$f" >/dev/null
+        "$mlton" "${flags[@]}" -output "$tmpf" "$f.mlb"
         if [ $? -ne 0 ]; then
-                compFail $f
+                compFail "$f"
         fi
-        rm -f $tmpf
+        rm -f "$tmpf"
     ;;
     esac
 done
 
-rm -f $tmp
+rm -f "$tmp"
