remove obsoleted cross-compilation options from ./bin/regression ([-cross target] [-resume test] [-run-only target])

diff --git a/bin/regression b/bin/regression
--- a/bin/regression
+++ b/bin/regression
@@ -8,15 +8,11 @@
 name=`basename "$0"`
 
 usage () {
-        echo >&2 "usage: $name [-cross target] [-resume test] [-run-only target] [-short] [-test-reg reg] [mlton flags ...]"
-        exit 1
+  echo >&2 "usage: $name [-fail] [-short] [-test-reg reg] [mlton flags ...]"
+  exit 1
 }
 
-cross='false'
 fail='false'
-resume='true'
-resumeTest='nil'
-runOnly='false'
 short='false'
 testReg='false'
 exitFail=false
@@ -26,56 +22,29 @@ declare -a extraFlags
 flags[${#flags[@]}]="-type-check"
 flags[${#flags[@]}]="true"
 while [ "$#" -gt 0 ]; do
-        case "$1" in
-        -cross)
-                cross='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                crossTarget="$1"
-                shift
-                ;;
-        -fail)
-                fail='true'
-                shift
-                ;;
-        -resume)
-                resume='false'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                resumeTest="$1"
-                shift
-                ;;
-        -run-only)
-                runOnly='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                crossTarget="$1"
-                shift
-                ;;
-        -short)
-                short='true'
-                shift
-                ;;
-        -test-reg)
-                testReg='true'
-                shift
-                if [ "$#" = 0 ]; then
-                        usage
-                fi
-                testRegs[${#testRegs[@]}]="$1"
-                shift
-                ;;
-        *)
-                flags[${#flags[@]}]="$1"
-		shift
-                ;;
-        esac
+  case "$1" in
+  -fail)
+          fail='true'
+          shift
+          ;;
+  -short)
+          short='true'
+          shift
+          ;;
+  -test-reg)
+          testReg='true'
+          shift
+          if [ "$#" = 0 ]; then
+                  usage
+          fi
+          testRegs[${#testRegs[@]}]="$1"
+          shift
+          ;;
+  *)
+          flags[${#flags[@]}]="$1"
+          shift
+          ;;
+  esac
 done
 
 
@@ -84,12 +53,6 @@ src=`cd "$dir/.." && pwd`
 bin="$src/build/bin"
 lib="$src/build/lib"
 mlton="$bin/mlton"
-if $cross; then
-	flags[${#flags[@]}]="-target"
-	flags[${#flags[@]}]="$crossTarget"
-	flags[${#flags[@]}]="-stop"
-	flags[${#flags[@]}]="g"
-fi
 cont='callcc.sml callcc2.sml callcc3.sml once.sml'
 flatArray='finalize.sml flat-array.sml flat-array.2.sml'
 intInf='conv.sml conv2.sml fixed-integer.sml harmonic.sml int-inf.*.sml slow.sml slower.sml smith-normal-form.sml'
@@ -101,7 +64,7 @@ PATH="$bin:$src/bin/.:$PATH"
 
 # whitelist tests that are known to fail (will still run but exit cleanly)
 declare -A whitelisted
-if [ -f  $src/regression/whitelist ] ; then
+if [ -a  $src/regression/whitelist ] ; then
   while read f ; do
     echo "whitelisting $f..."
     whitelisted["$f"]=1
@@ -116,7 +79,6 @@ isWhitelisted () {
     echo 0
   fi
 }
-
 
 eval `"$lib/platform"`
 
@@ -148,21 +110,9 @@ forMinGW='false'
 if [ `host-os` = mingw ]; then
 	forMinGW='true'
 fi
-case $crossTarget in
-*mingw)
-	forMinGW='true'
-;;
-esac
 
 for f in *.sml; do
         f=`basename "$f" .sml`
- 	if ! ($resume); then
-                if [ "$f" == "$resumeTest" ]; then
-                        resume='true'
-                else
-                        continue
-                fi
-        fi
         if ($testReg); then
                 skip='true'
                 for (( i = 0 ; $i < ${#testRegs[@]} ; i++ )); do
@@ -202,7 +152,7 @@ for f in *.sml; do
         serialize)
                 continue
         ;;
-	esac
+	      esac
         echo "testing $f"
         unset extraFlags
         case "$f" in
@@ -211,91 +161,63 @@ for f in *.sml; do
                 extraFlags[${#extraFlags[@]}]="Exn.keepHistory true"
         ;;
         esac
-	if (! $runOnly); then
-                mlb="$f.mlb"
-                echo "\$(SML_LIB)/basis/basis.mlb
-                        \$(SML_LIB)/basis/mlton.mlb
-                        \$(SML_LIB)/basis/sml-nj.mlb
-                        ann 
-                                \"allowFFI true\"
-                                \"allowOverload true\"
-                                \"allowExtendedTextConsts true\"
-                                \"nonexhaustiveBind ignore\"
-                                \"nonexhaustiveMatch ignore\"
-                                \"redundantBind ignore\"
-                                \"redundantMatch ignore\"
-                        in $f.sml 
-                        end" >"$mlb"
-                "$mlton" "${flags[@]}" "${extraFlags[@]}" -output "$f" "$mlb"
-                if [ "$?" -ne '0' ] || ((! $cross) && [ ! -x "$f" ]); then
-                        compFail "$f"
-                        exitFail=true
-                fi
-                rm "$mlb"
-	else
-                case "$crossTarget" in
-                *mingw)
-                        libs='-lws2_32 -lkernel32 -lpsapi -lnetapi32'
-                ;;
-                *solaris)
-                        libs='-lnsl -lsocket -lrt'
-                ;;
-                *)
-                        libs=''
-                ;;
-                esac
-                libs="-lmlton -lgmp $libs -lgdtoa -lm"
-                # Must use $f.[0-9].[csS], not $f.*.[csS], because the
-                # latter will include other files, e.g. for finalize,
-                # it will also include finalize.2. This happens only 
-		# when running cross regressions, which builds all the
-		# C files and saves them in this directory.
-		files="$f.[0-9].[csS]"
-		if [ 0 -ne `ls $f.[0-9][0-9].[csS] 2>/dev/null | wc -l` ]; then
-			files="$files $f.[0-9][0-9].[csS]"
-		fi
-                gcc -o "$f" -w -O1                              \
-                        -I "/usr/local/include" \
-                        -I "../build/lib/include"               \
-			-I "../build/lib/targets/$crossTarget/include"  \
-                        -L"../build/lib/targets/$crossTarget"           \
-                        -L/usr/pkg/lib                          \
-                        -L/usr/local/lib                        \
-                        $files $libs
-	fi
-        if [ ! -r "$f".nonterm -a $cross = 'false' -a -x "$f" ]; then
+
+        mlb="$f.mlb"
+        echo "\$(SML_LIB)/basis/basis.mlb
+                \$(SML_LIB)/basis/mlton.mlb
+                \$(SML_LIB)/basis/sml-nj.mlb
+                ann 
+                        \"allowFFI true\"
+                        \"allowOverload true\"
+                        \"allowExtendedTextConsts true\"
+                        \"nonexhaustiveBind ignore\"
+                        \"nonexhaustiveMatch ignore\"
+                        \"redundantBind ignore\"
+                        \"redundantMatch ignore\"
+                in $f.sml 
+                end" >"$mlb"
+        "$mlton" "${flags[@]}" "${extraFlags[@]}" -output "$f" "$mlb"
+        if [ "$?" -ne '0' ] || [ ! -x "$f" ]; then
+                compFail "$f"
+                exitFail=true
+        fi
+        rm "$mlb"
+
+        if [ ! -r "$f".nonterm -a -x "$f" ]; then
                 nonZeroMsg='Nonzero exit status.'
-		if $forMinGW; then
-                       nonZeroMsg="$nonZeroMsg"'\r'
-		fi
+                if $forMinGW; then
+                        nonZeroMsg="$nonZeroMsg"'\r'
+                fi
                 ( "./$f" || echo -e "$nonZeroMsg" ) >$tmp 2>&1 
                 if [ -r "$f.ok" ]; then
                         compare="$f.$HOST_ARCH-$HOST_OS.ok"
                         if [ ! -r $compare ]; then
                                 compare="$f.ok"
                         fi
-			if $forMinGW; then
+                        if $forMinGW; then
                                 newcompare="$f.sed.ok"
                                 sed $'s/$/\r/' <"$compare" > "$newcompare"
                                 compare="$newcompare"
-			fi
+                        fi
                         if ! diff "$compare" "$tmp"; then
                                 echo "$f: difference with ${flags[*]} ${extraFlags[*]}"
                                 ignore=$(isWhitelisted $f)
-                                if [ "$ignore" -eq 0 ] ; then 
+                                if [ "$ignore" -eq 0 ] ; then
                                   exitFail=true
                                 fi
                         fi
                 fi
         fi
 done
-if $cross || $runOnly || $short || $testReg ; then
+
+if $short || $testReg ; then
   if [ "$exitFail" = true ] ; then
     exit 1
   else
     exit 0
   fi
 fi
+
 mmake clean >/dev/null
 cd "$src/benchmark/tests"
 for f in *.sml; do
@@ -321,7 +243,7 @@ for f in *.sml; do
                 rm -f "$tmpf" "$tmpf.sml"
         ;;
         esac
-done 
+done
 mmake clean >/dev/null
 cd "$src"
 for f in mllex mlyacc mlprof; do
