MAIL MLton now runs on Darwin!
Incorporated Filip Pizlo's patch to make MLton run on Darwin.  All in
all a quite small patch, showing how easy it is to port MLton to a new
(unix-ish) platform using the C codegen.

All regressions pass except for real, which has a few differences in
low-order bits on some tests.

Self compile works without problems.

I reworked the handling of the constants MLton_Platform_{Arch,OS}_host
so that they are set to string constants in the appropriate
runtime/platform/*.h file, and the string constants are checked in
basis-library/misc/primitive.sml.  This makes it possible to add a new
platform without modifying existing ones.  It did stress compile-time
string constants, which were otherwise unused.  Right now, I'm not
doing any escaping of them, so that the string constants can not
contain spaces or other funny characters.

diff --git a/bin/upgrade-basis b/bin/upgrade-basis
--- a/bin/upgrade-basis
+++ b/bin/upgrade-basis
@@ -25,6 +25,11 @@ esac
 
 tmp="$$.sml"
 
+echo "val () = print \"I work\"" >$tmp
+if ! mlton $tmp 1>&2; then
+	die "Error: cannot upgrade basis because the compiler doesn't work" 
+fi
+
 feature () {
 	feature="$1"
 	sml="$2"
@@ -90,6 +95,9 @@ structure LargeWord = Word'
 
 eval `$bin/platform`
 case $HOST_ARCH in
+powerpc)
+	arch='PowerPC'
+;;
 sparc)
 	arch='Sparc'
 ;;
@@ -103,6 +111,9 @@ esac
 case $HOST_OS in
 cygwin)
 	os='Cygwin'
+;;
+darwin)
+	os='Darwin'
 ;;
 freebsd)
 	os='FreeBSD'
@@ -140,9 +151,11 @@ structure MLton =
 
             structure Arch =
                struct
-                  datatype t = Sparc | X86
+                  datatype t = PowerPC | Sparc | X86
 
-                  val all = [(Sparc, "Sparc"), (X86, "X86")]
+                  val all = [(PowerPC, "PowerPC"), 
+                             (Sparc, "Sparc"), 
+                             (X86, "X86")]
 
                   fun fromString s =
                      let
@@ -153,15 +166,21 @@ structure MLton =
 
                   val host = $arch
 
+                  val isBigEndian =
+                    fn PowerPC => true
+                     | Sparc => true
+                     | X86 => false
+
                   fun toString a = #2 (valOf (peek (all, fn (a', _) => a = a')))
                end
 
             structure OS =
                struct
-                  datatype t = Cygwin | FreeBSD | Linux | MinGW | NetBSD 
+                  datatype t = Cygwin | Darwin | FreeBSD | Linux | MinGW | NetBSD
                              | OpenBSD | Solaris
 
                   val all = [(Cygwin, "Cygwin"),
+                             (Darwin, "Darwin"),
                              (FreeBSD, "FreeBSD"),
                              (Linux, "Linux"),
                              (MinGW, "MinGW"),
